import { config as baseConfig } from "@patricktree-stack/config-oxlint/oxlint-base.js";
import { defineConfig } from "oxlint";

export default defineConfig({
  extends: [baseConfig],
  /* `plugins` overwrites the base set instead of merging, so the base plugins are repeated here */
  plugins: [
    ...(baseConfig.plugins ?? []),
    /* oxlint implements all 21 rules of `@next/eslint-plugin-next` natively */
    "nextjs",
  ],
  /* `next-env.d.ts` is generated by Next.js and must not be edited */
  ignorePatterns: ["next-env.d.ts"],
  rules: {
    /* Next.js compiles JSX with the automatic runtime, so `React` does not need to be in scope */
    "react/react-in-jsx-scope": "off",
  },
});
